sudo: required
env:
  secure: "HcZPrs53irGBga3wuqz9LK5C53Z0LRrzbZjXlZu/l5K+z18Lt4Ll1+ZY6vnna0U2W4JOo5jQ//jtLixG5tb871FyGfsd18yGK/ANtb95LNV1YAIcICn6UeQg3gbhC57NZpfTlJFjXHEnlKwSliVo+Dz6F1Et1VIMW0rOWpgGXhXhvXmBMJ5BCBVQVw0sqDQD2bZKFnOtohbGLAQ8bNqqhpIRgb+958lqMuJudPtzQs0lAUZ3AtGUBNyTd1tQ39T/SmMoXAFxndElsgK9m1+AToumILspZKeUSkWVUYlHKElfpGI0bySCds7KLN/Z8izUGmczcTEr3wKN/sIpwEyLvRSCVH+R40s7VM8cN0NDPf68C4Jg/nwAPn5MuNnKJaiB81l+VKm50nG/VsQEDDG3Tm5lBnhJp3/LTUol1Q0vQaiCrViBjnzFDBstkTQMyQjKRgX5g27otsZgdLmDcGWY9csRKUksQOU9Su6Z/JVgkmJ6LuqmjqmeVLkmJ8knJga6Dor3M/HwpVIWaHlAMUnBXLeixbm2T89RFkTY1qZE5vEQaqDUpx9Yh4pAlrCSHcEkYvhTIlEZfmsEw1I7ui4FkCu4zPDV5BuAheBbessOjlXO3CpR9msw0nYhX4kC+DXdPR0JI2k/a/HGMPSSRYE96+KULOm6EXA1mgJVCs4DDDM="
services:
- docker
install:
- docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
script:
- docker build -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME
