sudo: required
env:
  global:
    secure: ceVTnpxyi/dOJg6eOlY/hxaPXqv3dW9Xwb8v5nFmI3r0BhlgVD7c7lInjjmY2K0c4LQZZh0T9uhUSST0CuuJhbut1A5XbvnsERvzcS4ikkgl1d4M9fbuzZc0gQhD7iAfpHEZE1/Ns+wTY5DA7/qWCUnBMvbMJK0tG5kKqbB/Xl53+0KeTBCf7Ggbc0VOsH834NtD1xKeXgfDBOUCPlM93rf1j18w4Pys7uLp4tsZBMxtBB6o0oljxawPKldRKoXZlvwd1BqWb/OGONZQoNTnP844NM3MzXodvyOAwXkLGBCiGS84IiqNkbK16IlTH35zcBt3An/EX9yPSaPXHbWLQ1EK/UcwFEUb6ycSOjUM2NVWxsLg8F7Yxj1plSqLsgeZyEmKknHPfthX7IoWC/UoOm20emy/QmpJPc+QtQP1ScUx8xNQ3ysjbHWg8cuA3qNmppu20XMdX5Ssu6uT9d5eBgNvloHvXARJqOAtBQWajlTWFUXRsCu11bXn1muEK1uexbxjPxku024ZhftRuNWQ20H26XV0IbxJwc3sp3ReIMZoF1ILoqDVxCSJjET10XRcZJdvAUJFOirX9DLekVziFldS+FWYvDHcWAWSA3WIk1mWrYWoJVs4c8olEBO4lpEiTGMn7FdJekrgSh3OW8dcVwoOgNVn4kPAuvQe2r06mOE=
services:
- docker
install:
- docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
script:
- docker build -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi && docker push $DOCKER_IMAGE_NAME
